#!/bin/bash

# https://github.com/yangziwen/diff-check/blob/master/hooks/pre-commit-checkstyle

GIT_ROOT_DIR=$(git rev-parse --show-toplevel)
GIT_HOOK_DIR=$(git config --get core.hooksPath)
if [ ! -d "$GIT_HOOK_DIR" ]; then
  GIT_HOOK_DIR="$GIT_ROOT_DIR/.git/hooks"
fi

CHECKSTYLE_JAR="$GIT_HOOK_DIR/diff-checkstyle.jar"
if [ ! -f "$CHECKSTYLE_JAR" ]; then
  echo "$CHECKSTYLE_JAR does not exist!"
  echo
  exit 0
fi

SUN_CHECKS="/sun_checks.xml"
GOOGLE_CHECKS="/google_checks.xml"
CHECKSTYLE_CONFIG=$SUN_CHECKS
if [[ "$CHECKSTYLE_CONFIG" != "$SUN_CHECKS" &&
  "$CHECKSTYLE_CONFIG" != "$GOOGLE_CHECKS" &&
  ! -f "$CHECKSTYLE_CONFIG" ]]; then
  echo "$CHECKSTYLE_CONFIG does not exist!"
  echo
  exit 0
fi

# Check whether this is the first commit
git log --oneline -1 >/dev/null 2>&1
result=$?
if [ $result -ne 0 ]; then
  exit 0
fi

echo "=== Checkstyle ==="
echo "Configuration file used: $CHECKSTYLE_CONFIG"
java -jar "$CHECKSTYLE_JAR" -c "$CHECKSTYLE_CONFIG" "$GIT_ROOT_DIR" --git-dir "$GIT_ROOT_DIR" --include-staged-codes
result=$?
if [ $result -ne 0 ]; then
  echo "Please fix the checkstyle problems before submitting the commit!"
  echo
  exit $result
fi

exit 0
