#!/bin/bash

MESSAGE=$(cat "$1")
TICKET=$(git rev-parse --abbrev-ref HEAD | grep -Eo "\w+-[0-9]+_" | cut -d "_" -f 1)

if [[ "$TICKET" =~ [a-z]+ ]]; then
    echo "> WARN: ticket $TICKET contains lowercase character(s) in its name!"
fi

if [[ -z "$TICKET" || "$MESSAGE" == "$TICKET "* ]]; then
  exit 0
fi

echo "> Ticket not found in commit message!"
echo "> Add prefix [$TICKET] to commit message"
echo "[$TICKET] $MESSAGE" > "$1"
